{% set name = "fluoriclogppka" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fluoriclogppka-{{ version }}.tar.gz
  sha256: c5cda102def8229b8fe39c0a3cca7355b075252b44f3fee348db3a9369be00e5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11
    - pip
  run:
    - python >=3.11
    - certifi ==2024.2.2
    - charset-normalizer ==3.3.2
    - future ==1.0.0
    - h2o-py ==3.44.0.3
    - idna ==3.6
    - mordred ==1.2.0
    - networkx ==2.8.8
    - numpy >=1.26.4
    - openpyxl ==3.1.4
    - packaging ==24.0
    - pandas >=2.2.0
    - pillow >=9.2.0
    - python-dateutil ==2.8.2
    - pytz ==2024.1
    - rdkit ==2022.9.5
    - requests ==2.31.0
    - six >=1.16.0
    - tabulate ==0.9.0
    - urllib3 ==2.2.1
    - pytorch ==2.0.0
    - torchvision ==0.15.1
    - dgl ==1.1.2
    - dgllife ==0.3.2
    - torchdata >=0.6.0
    - pyyaml ==6.0.1
    - pydantic ==2.5.3

test:
  imports:
    - fluoriclogppka
  commands:
    - pip check || true  # We allow the check to fail because of a problem with rdkit, because the rdkit package is missing the required pip installation information.
  requires:
    - pip

about:
  home: https://github.com/blackthorn-ai/fluoricLogPpKa
  summary: Tool for pKa, logP prediction
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - PetroPavliukk
    - ogurbych
    - DkraAI
